# https://sharphook.tolik.io/articles/keycodes.html
modmap:
  - name: Keys
    remap:
      CapsLock: Super_L
      Super_L: Shift_L
      Alt_R: Ctrl_L
#      Ctrl_R: Shift_L

keymap:
  - name: Alt keys
    remap:
      Alt-h: left
      Alt-j: down
      Alt-k: up
      Alt-l: right
      Alt-w: backspace # for now to learn
      #Alt-w: reserved # for now to learn
      Alt-f: backspace
      Alt-m: Enter
      Alt-i: Esc
      Alt-u: Esc
      Esc: reserved

      # If you hash sysrq 5 times and reverse the letters, you will get prtsc,
      # so this is obviously(.) print screen key.
      # doesn't work now. WTF
      sysrq:
        launch: ["flameshot", "gui"]

      #Alt-e: reserved # for now to learn

      Super-z:
        remap:
          u:
            launch: ["/usr/local/bin/dmenu_unicode/launch.sh"]
          b:
            launch: ["/home/artarar/shortcuts/bugg"]
          c:
            launch: ["/usr/bin/copyq", "show"]
